### PR TITLE
Fail measurements if any of the jobs returned issues

### PR DESCRIPTION
**Pull request by olichtne**
### Description
This is necessary to detect situation when something went wrong with the measurement and we should disqualify the measurement results from being fully trustworthy, e.g. for setting baselines.

### Tests
Needs to be tested for all types of measurements, ideally with failures in the measurement process to see the changed results.

### Reviews
@Axonis @enhaut @jtluka 

Closes: #

### CODE REVIEW

**Review by Axonis — APPROVED** [review]
Briefly discussed offline, as a hotfix to get rid of 0 measurements messing with rolling baselines this is good enough.

However moving forward, it would be better to either move some functionality of measurements to results or vice versa.

**Comment by jtluka** [comment]
Looks good.

**Review by jtluka — DISMISSED** [review]

**Comment by olichtne** [comment]
testing done internally in beaker job `J:10274482`

i believe this is ready to be merged.

**Comment by jtluka** [comment]
Ack to merge.

**Pull request merged**
