### PR TITLE
pyproject.toml: limit urllib3 version

### PR DESCRIPTION
**Pull request by olichtne**
### Description
Should fix issues with docker-python we see in CI.

https://github.com/docker/docker-py/issues/3113

### Tests
CI tests are enough.

### Reviews
(Please add a list of reviewers that should check the validity and sanity of
this merge request before it's accepted. Use the `@username` syntax. If you
don't know who to mention just link `@all`.)

Closes: #

### CODE REVIEW

**Review by enhaut — COMMENTED** [review]
This has already been fixed in https://github.com/containers/podman-py/pull/265, but it hasn't been released yet, shouldn't we just wait?

**Comment by olichtne** [comment]
> This has already been fixed in [containers/podman-py#265](https://github.com/containers/podman-py/pull/265), but it hasn't been released yet, shouldn't we just wait?

well the don't really seem to have a regular release schedule. I'd rather have a functional CI and then remove this once the update is in place, whenever that may happen. What do you think?

**Comment by jtluka** [comment]
Could you check if this integrates well in our downstream deployment?

**Review by jtluka — APPROVED** [review]

**Comment by olichtne** [comment]
scheduled some internal tests: `J:7862577` and `J:7862578`

**Comment by olichtne** [comment]
tests finished fine, merging.

**Pull request merged**
