### PR TITLE
Use device.up_and_wait() in some recipes

### PR DESCRIPTION
**Pull request by Kuba314**
### Description
Wait for devices in some recipes to be ready.

### Tests
`J:8008514`

### Reviews
@LNST-project/lnst-developers 

Closes: #100

### CODE REVIEW

**Review by olichtne — COMMENTED** [review]
looks, ok but i want to see this tested before merging in.

**Comment by Kuba314** [comment]
@jtluka I selected all recipes that are in internal tests tagged with cnb.

Anyways, I now changed only the recipes you specified.

@olichtne how would I test this? Just run the affected recipes and see if it doesn't throw?

**Comment by enhaut** [comment]
> @olichtne how would I test this? Just run the affected recipes and see if it doesn't throw?
Yes, just run one test of each affected recipe

**Comment by Kuba314** [comment]
Tested each recipe in Beaker job J:7992869. Seems to work fine.

**Review by olichtne — COMMENTED** [review]
> J:7992869

there are two tests that don't have thresholds, i assume that's just an oversight when running job-generator and selecting which tests to run?

**Comment by Kuba314** [comment]
Didn't notice these tests had no thresholds set. Rerunning the previous working tests and 2 new ones at J:8008466.

**Comment by Kuba314** [comment]
All 8 tests passed.

**Review by olichtne — APPROVED** [review]
looks ok after live discussion on a meeting.

**Pull request merged**
